version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            - v1-dependencies-
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Run Unit tests
          command: ./gradlew test
      - run:
          name: Assemble build
          command: ./gradlew assemble
      - run:
          name: Publish Maven artifact
          command: ./gradlew publish
      - store_artifacts:
          path: build/repository
          destination: repository
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results