version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            - v1-dependencies-
      - run:
          name: Check dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run Unit tests
          command: ./gradlew test
      - run:
          name: Assemble build
          command: ./gradlew assemble
      - run:
          name: Increase version
          command: |
            git config --global user.name $GIT_USERNAME
            git config --global user.email $GIT_USEREMAIL
            git clone https://github.com/dvpermyakov/increment-version-bash.git
            cd increment-version-bash/
            chmod u+x ./increment.sh
            ./increment.sh -r $CIRCLE_REPOSITORY -b $CIRCLE_BRANCH -m master -f version.txt
      - run:
          name: Publish Maven artifact
          command: ./gradlew publish
      - run:
          name: Upload to Bintray
          command: |
            if [ "$CIRCLE_BRANCH" = "master" ]; then
              ./gradlew bintrayUpload
            fi
      - store_artifacts:
          path: build/repository
          destination: repository
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results